//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace wa_transcript
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class tmp_javsEntities : DbContext
    {
        public tmp_javsEntities()
            : base("name=tmp_javsEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<inf_Event> inf_Event { get; set; }
        public virtual DbSet<inf_Master> inf_Master { get; set; }
        public virtual DbSet<inf_Media> inf_Media { get; set; }
        public virtual DbSet<inf_Session> inf_Session { get; set; }
    }
}
