//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace wa_transcript
{
    using System;
    using System.Collections.Generic;
    
    public partial class inf_Media
    {
        public int MediaId { get; set; }
        public string Path { get; set; }
        public string DeviceId { get; set; }
        public string Height { get; set; }
        public string Width { get; set; }
        public string Incomplete { get; set; }
        public System.Guid id_control { get; set; }
    
        public virtual inf_Master inf_Master { get; set; }
    }
}
