//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace wa_transcript
{
    using System;
    using System.Collections.Generic;
    
    public partial class inf_Master
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public inf_Master()
        {
            this.inf_Event = new HashSet<inf_Event>();
            this.inf_Media = new HashSet<inf_Media>();
            this.inf_Session = new HashSet<inf_Session>();
        }
    
        public System.Guid id_control { get; set; }
        public Nullable<System.Guid> MasterId { get; set; }
        public string Id { get; set; }
        public string Title { get; set; }
        public string Department { get; set; }
        public string IsSealed { get; set; }
        public string Exhibits { get; set; }
        public Nullable<int> id_estatus { get; set; }
        public Nullable<System.DateTime> fecha_registro { get; set; }
        public Nullable<System.Guid> id_centro { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<inf_Event> inf_Event { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<inf_Media> inf_Media { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<inf_Session> inf_Session { get; set; }
    }
}
